
server:
  port: 8089
  tomcat:
    uri-encoding: UTF-8

spring:
  application:
    name: xp-ican-boot
  profiles:
    active: local

  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false

  aop:
    proxy-target-class: true
    auto: true

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ican?characterEncoding=utf8&useSSL=false&autoReconnect=true&serverTimezone=GMT%2B8&zeroDateTimeBehavior=convertToNull
    username: root
    password: liangqinwei
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-init-sql: SET NAMES utf8mb4


mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.xp.ican.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
  global-config:
    db-config:
      id-type: auto
      field-strategy: not_null
      table-underline: true
      logic-delete-value: 1
      logic-not-delete-value: 0


xiaopeng:
  vehicle:
    common:
      bodyExcludeUrl:
        - /prometheus
        - /health
        - /info

jwt:
  appKey:
  period:
  issuer:
